version: '3'

services:
  web:
    build:
      context: . 
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html/
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
    - ./www:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: esgi  
      POSTGRES_USER: esgi
      POSTGRES_PASSWORD: esgipwd
    ports:
      - '5432:5432'
    volumes:
        - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "melina.terrier@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test" 
    ports:
      - 5050:80 
    depends_on:
      - postgres

volumes:
  pgdata:
