version: '3'
services:
  web:
    build: . 
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgres

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www/html
      - ./letsencrypt:/etc/letsencrypt
      - ./nginx/certbot:/var/www/certbot
    depends_on:
      - web

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: esgi  
      POSTGRES_USER: esgi
      POSTGRES_PASSWORD: esgipwd
    ports:
      - '5432:5432'
    volumes:
        - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "melina.terrier@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test" 
    ports:
      - 5050:80 
    depends_on:
      - postgres

volumes:
  pgdata:
