version: '3'
services:
  web:
    build: site
    ports:
      - "8081:80"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
    networks:
      - default

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: esgi  
      POSTGRES_USER: esgi
      POSTGRES_PASSWORD: esgipwd
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "melina.terrier@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test" 
    ports:
      - 5050:80 
    depends_on:
      - postgres
    networks:
      - default

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./www:/var/www/html
      - ./nginx/certs:/etc/nginx/certs:ro  # Mount the certs directory
    depends_on:
      - web
    networks:
      - default

networks:
  default:
    external:
      name: challenge-3iwj_default
