version: '3'
services:
  web:
    build: . 
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - postgres
<<<<<<< HEAD

=======
<<<<<<< HEAD
=======
    
>>>>>>> 2b6e607 (mise en place de la vérification du statut de l'user)
>>>>>>> 831169c (mise en place des formulaires)
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: esgi  
      POSTGRES_USER: esgi
      POSTGRES_PASSWORD: esgipwd
    ports:
<<<<<<< HEAD
      - '5432:5432'
    # volumes:
    #   - ./Script.sql:/docker-entrypoint-initdb.d/Script.sql

=======
      - '5433:5432'
<<<<<<< HEAD
    volumes:
      - ./Script.sql:/docker-entrypoint-initdb.d/Script.sql
=======

>>>>>>> 2b6e607 (mise en place de la vérification du statut de l'user)
>>>>>>> 831169c (mise en place des formulaires)
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "melina.terrier@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "test" 
    ports:
      - 5050:80 
    depends_on:
      - postgres
