# BACK-OFFICE
/dashboard:
  Controller: "Main"
  Action: "dashboard"
  Security: true
  Role: ["Administrateur"]

# USER
/dashboard/users:
  Controller: "UserController"
  Action: "allUsers"
  Security: true
  Role: ["Administrateur"]

/dashboard/user:
  Controller: "UserController"
  Action: "addUser"
  Security: true
  Role: ["Administrateur"]

# PROJECT
/dashboard/project:
  Controller: "Project"
  Action: "addProject"
  Security: true
  Role: ["Administrateur", "Utilisateur"]

/dashboard/projects:
  Controller: "Project"
  Action: "allProjects"
  Security: true
  Role: ["Administrateur"]

# PAGE
/dashboard/page:
  Controller: "Page"
  Action: "addPage"
  Security: true
  Role: ["Administrateur"]

/dashboard/pages:
  Controller: "Page"
  Action: "allPages"
  Security: true
  Role: ["Administrateur"]


# Comments
/dashboard/comments:
  Controller: "Comment"
  Action: "allComments"
  Security: true
  Role: ["Administrateur"]
 

# TAGS
/dashboard/tag:
  Controller: "Tag"
  Action: "addTag"
  Security: true
  Role: ["Administrateur"]

/dashboard/tags:
  Controller: "Tag"
  Action: "allTags"
  Security: true
  Role: ["Administrateur"]

# MEDIAS
/dashboard/medias:
  Controller: "Media"
  Action: "allMedias"
  Security: true
  Role: ["Administrateur"]

/dashboard/add-media:
  Controller: "Media"
  Action: "addMedia"
  Security: true
  Role: ["Administrateur"]

/dashboard/edit-media:
  Controller: "Media"
  Action: "editMedia"
  Security: true
  Role: ["Administrateur"]

# SETTING
/dashboard/settings:
  Controller: "Settings"
  Action: "setSetting"
  Security: true
  Role: ["Administrateur"]

/dashboard/menu:
  Controller: "Settings"
  Action: "setMenu"
  Security: true
  Role: ["Administrateur"]

/dashboard/appearance:
  Controller: "Settings"
  Action: "setAppearance"
  Security: true
  Role: ["Administrateur"]

/dashboard/menus:
  Controller: "Settings"
  Action: "allMenu"
  Security: true
  Role: ["Administrateur"]


# FRONT
/:
  Controller: "Main"
  Action: "home"

/search: 
  Controller: "Main"
  Action: "displayResult"


# USER
/profile/edit:
  Controller: "UserController"
  Action: "editUser"
  Security: true
  Role: ["Utilisateur", "Editeur", "Administrateur"]

/profile/edit-password:
  Controller: "UserController"
  Action: "editPassword"
  Security: true
  Role: ["Utilisateur", "Editeur", "Administrateur"]

/login:
  Controller: "Security"
  Action: "login"

/register:
  Controller: "Security"
  Action: "register"

/activate-account:
  Controller: "Security"
  Action: "activateAccount"

/logout:
  Controller: "Security"
  Action: "logout"

/reset-password:
  Controller: "Security"
  Action: "resetPassword"

/request-password:
  Controller: "Security"
  Action: "requestPassword"

  