/:
  Controller: "Main"
  Action: "home"

# BACK-OFFICE
/dashboard:
  Controller: "Main"
  Action: "dashboard"
  Security: true
  # Role: [admin]

/edit-user:
  Controller: "User"
  Action: "editUser"

/show-user:
  Controller: "User"
  Action: "showUser"

# USER
/dashboard/users:
  Controller: "User"
  Action: "allUsers"
  Security: true
  # Role: [admin]

/dashboard/add-user:
  Controller: "User"
  Action: "addUser"
  Security: true
  # Role: [admin]

/dashboard/view-user:
  Controller: "User"
  Action: "viewUser"
  Security: true
  # Role: [admin]

/dashboard/edit-user:
  Controller: "User"
  Action: "addUser"
  Security: true
  # Role: [user, admin]

/profile:
  Controller: "User"
  Action: "editUser"
  Security: true
  # Role: [user, admin]

# PROJECT
/dashboard/add-project:
  Controller: "Project"
  Action: "addProject"
  Security: true
  # Role: [admin]

/dashboard/projects:
  Controller: "Project"
  Action: "allProjects"
  Security: true
  # Role: [admin]

/dashboard/edit-project:
  Controller: "Project"
  Action: "editProject"
  Security: true
  # Role: [admin]

# PAGE
/dashboard/add-page:
  Controller: "Page"
  Action: "addPage"
  Security: true
  # Role: [admin]

/dashboard/edit-page:
  Controller: "Page"
  Action: "editPage"
  Security: true
  # Role: [admin]

/dashboard/pages:
  Controller: "Page"
  Action: "allPages"
  Security: true
  # Role: [admin]

/dashboard/comments:
  Controller: "Comment"
  Action: "allComments"
  Security: true
  # Role: [admin]

# /dashboard/add-comment:
#   Controller: "Comment"
#   Action: "addComment"
  # Security: true
  # Role: "admin"

# TAGS
/dashboard/add-tag:
  Controller: "Tag"
  Action: "addTag"
  Security: true
  # Role: "admin"

/dashboard/edit-tag:
  Controller: "Tag"
  Action: "editTag"
  Security: true

/dashboard/tags:
  Controller: "Tag"
  Action: "allTags"
  Security: true
  # Role: [admin]

# MEDIAS
/dashboard/medias:
  Controller: "Media"
  Action: "allMedias"
  Security: true
  # Role: [admin]

/dashboard/add-media:
  Controller: "Media"
  Action: "addMedia"
  Security: true
  # Role: "admin"

/dashboard/edit-media:
  Controller: "Media"
  Action: "editMedia"
  Security: true
  # Role: "admin"

# SETTING
/dashboard/settings:
  Controller: "Settings"
  Action: "setSetting"
  Security: true
  # Role: [admin]


# USER
/login:
  Controller: "Security"
  Action: "login"

/register:
  Controller: "Security"
  Action: "register"

/activate-account:
  Controller: "Security"
  Action: "activateAccount"

/logout:
  Controller: "Security"
  Action: "logout"

/reset-password:
  Controller: "Security"
  Action: "resetPassword"

/request-password:
  Controller: "Security"
  Action: "requestPassword"