/:
  Controller: "Main"
  Action: "home"

# BACK-OFFICE
/dashboard:
  Controller: "Main"
  Action: "dashboard"
  Security: true
  Role: ["Administrateur"]

# USER
/dashboard/users:
  Controller: "User"
  Action: "allUsers"
  Security: true
  Role: ["Administrateur"]

/dashboard/add-user:
  Controller: "User"
  Action: "addUser"
  Security: true
  Role: ["Administrateur"]

/dashboard/edit-user:
  Controller: "User"
  Action: "addUser"
  Security: true
  Role: ["Administrateur"]

# PROJECT
/dashboard/add-project:
  Controller: "Project"
  Action: "addProject"
  Security: true
  Role: ["Administrateur", "Utilisateur"]

/dashboard/projects:
  Controller: "Project"
  Action: "allProjects"
  Security: true
  Role: ["Administrateur"]

/dashboard/edit-project:
  Controller: "Project"
  Action: "editProject"
  Security: true
  Role: ["Administrateur"]

# PAGE
/dashboard/add-page:
  Controller: "Page"
  Action: "addPage"
  Security: true
  Role: ["Administrateur"]

/dashboard/edit-page:
  Controller: "Page"
  Action: "editPage"
  Security: true
  Role: ["Administrateur"]

/dashboard/pages:
  Controller: "Page"
  Action: "allPages"
  Security: true
  Role: ["Administrateur"]

# Comments
/dashboard/comments:
  Controller: "Comment"
  Action: "allComments"
  Security: true
  Role: ["Administrateur"]

# TAGS
/dashboard/add-tag:
  Controller: "Tag"
  Action: "addTag"
  Security: true
  Role: ["Administrateur"]

/dashboard/edit-tag:
  Controller: "Tag"
  Action: "editTag"
  Security: true
  Role: ["Administrateur"]

/dashboard/tags:
  Controller: "Tag"
  Action: "allTags"
  Security: true
  Role: ["Administrateur"]

# MEDIAS
/dashboard/medias:
  Controller: "Media"
  Action: "allMedias"
  Security: true
  Role: ["Administrateur"]

/dashboard/add-media:
  Controller: "Media"
  Action: "addMedia"
  Security: true
  Role: ["Administrateur"]

/dashboard/edit-media:
  Controller: "Media"
  Action: "editMedia"
  Security: true
  Role: ["Administrateur"]

# SETTING
/dashboard/settings:
  Controller: "Settings"
  Action: "setSetting"
  Security: true
  Role: ["Administrateur"]

# USER
/login:
  Controller: "Security"
  Action: "login"

/register:
  Controller: "Security"
  Action: "register"

/activate-account:
  Controller: "Security"
  Action: "activateAccount"

/logout:
  Controller: "Security"
  Action: "logout"

/reset-password:
  Controller: "Security"
  Action: "resetPassword"

/request-password:
  Controller: "Security"
  Action: "requestPassword"