/:
  Controller: "Main"
  Action: "home"


/login:
  Controller: "Security"
  Action: "login"

/register:
  Controller: "Security"
  Action: "register"

/logout:
  Controller: "Security"
  Action: "logout"

/update:
  Controller: "Security"
  Action: "update"

/comment:
  Controller: "Security"
  Action: "comment"

/newsletter:
  Controller: "Security"
  Action: "newsletter"

/reinitialization:
  Controller: "Security"
  Action: "reinitialization"

/ajout-utilisateur:
  Controller: "User"
  Action: "add"

/del-utilisateur:
  Controller: "User"
  Action: "delete"

/show-utilisateur:
  Controller: "User"
  Action: "show"

/list-utilisateurs:
  Controller: "User"
  Action: "list"

/maj-utilisateurs:
  Controller: "User"
  Action: "edit"
