/:
  Controller: "Main"
  Action: "home"


/login:
  Controller: "Security"
  Action: "login"

/register:
  Controller: "Register"
  Action: "register"

/logout:
  Controller: "Security"
  Action: "logout"

/update:
  Controller: "Update"
  Action: "update"

/comment:
<<<<<<< HEAD
  Controller: "CommentController"
  Action: "comment"

/project:
  Controller: "ProjectController"
  Action: "project"

/category:
  Controller: "CategoryController"
  Action: "category"




=======
  Controller: "Comment"
  Action: "comment"


/category:
  Controller: "Category"
  Action: "category"

/media:
  Controller: "Media"
  Action: "media"

/project:
  Controller: "Project"
  Action: "project"

/setting:
  Controller: "Setting"
  Action: "setting"  

/page:
  Controller: "Page"
  Action: "page" 

/theme:
  Controller: "Theme"
  Action: "theme"

/reinitialization:
  Controller: "Reinitialization"
  Action: "reinitialization"
>>>>>>> 6c501f1db55d62bf1e1edcc546dfce12f25dc3b4

/ajout-utilisateur:
  Controller: "User"
  Action: "add"

/del-utilisateur:
  Controller: "User"
  Action: "delete"

/show-utilisateur:
  Controller: "User"
  Action: "show"

/list-utilisateurs:
  Controller: "User"
  Action: "list"

/maj-utilisateurs:
  Controller: "User"
  Action: "edit"
