/:
  Controller: "Main"
  Action: "home"

# BACK-OFFICE
/dashboard:
  Controller: "Main"
  Action: "dashboard"
  Security: true
  # Role: [admin]

# USER
/dashboard/users:
  Controller: "User"
  Action: "allUsers"
  Security: true
  # Role: [admin]

/dashboard/add-user:
  Controller: "User"
  Action: "addUser"
  Security: true
  # Role: [admin]

/dashboard/profile:
  Controller: "User"
  Action: "viewUser"
  Security: true
  # Role: [admin]

/dashboard/edit-user:
  Controller: "User"
  Action: "editUser"
  Security: true
  # Role: [user, admin]

# PROJECT
/dashboard/add-project:
  Controller: "Project"
  Action: "addProject"
  Security: true
  # Role: [admin]

/dashboard/projects:
  Controller: "Project"
  Action: "allProjects"
  Security: true
  # Role: [admin]

# PAGE
/dashboard/add-page:
  Controller: "Page"
  Action: "addPage"
  Security: true
  # Role: [admin]

/dashboard/pages:
  Controller: "Page"
  Action: "allPages"
  Security: true
  # Role: [admin]

/dashboard/comments:
  Controller: "Comment"
  Action: "allComments"
  Security: true
  # Role: [admin]

/dashboard/add-comment:
  Controller: "Comment"
  Action: "addComment"
  # Security: true
  # Role: "admin"

# TAGS
/dashboard/add-tag:
  Controller: "Tag"
  Action: "addTag"
  Security: true
  # Role: "admin"

/dashboard/tags:
  Controller: "Tag"
  Action: "allTags"
  Security: true
  # Role: [admin]

# MEDIAS
/dashboard/medias:
  Controller: "Media"
  Action: "allMedias"
  Security: true
  # Role: [admin]

/dashboard/add-media:
  Controller: "Media"
  Action: "addMedia"
  Security: true
  # Role: "admin"


# SETTING
/dashboard/settings:
  Controller: "Setting"
  Action: "setSetting"
  Security: true
  # Role: [admin]


# INSTALLER
/install:
  Controller: "Installer"
  Action: "Install"



# USER
/login:
  Controller: "Security"
  Action: "login"

/register:
  Controller: "Security"
  Action: "register"

/activate-account:
  Controller: "Security"
  Action: "activateAccount"


/logout:
  Action: "logout"

/reset-password:
  Controller: "Security"
  Action: "resetPassword"

/request-password:
  Controller: "Security"
  Action: "requestPassword"

