/:
  Controller: "Main"
  Action: "home"
  C: false
  Role: ""


# BACK-OFFICE
/dashboard:
  Controller: "Main"
  Action: "dashboard"
  Security: true
  # Role: [admin]


# USER
/dashboard/users:
  Controller: "User"
  Action: "allUsers"
  Security: true
  # Role: [admin]

/dashboard/add-user:
  Controller: "User"
  Action: "addUser"
  Security: true
  # Role: [admin]

/dashboard/profile:
  Controller: "User"
  Action: "viewUser"
  Security: true
  # Role: [admin]

/dashboard/edit-user:
  Controller: "User"
  Action: "editUser"
  Security: true
  # Role: [user, admin]

# /dashboard/delete-user:
#   Controller: "User"
#   Action: "delete"
#   Security: true
#   Role: "admin, user"

# PROJECT
/dashboard/add-project:
  Controller: "Project"
  Action: "addProject"
  Security: true
  # Role: [admin]


/dashboard/projects:
  Controller: "Project"
  Action: "allProjects"
  Security: true
  # Role: [admin]

# /dashboard/delete-project:
#   Controller: "Project"
#   Action: "delete"
#   Security: true
#   Role: "admin, user"

# /dashboard/update-project:
#   Controller: "Project"
#   Action: "edit"
#   Security: true
#   Role: "user, admin"


# PAGE
/dashboard/add-page:
  Controller: "Page"
  Action: "addPage"
  Security: true
  # Role: [admin]

/dashboard/pages:
  Controller: "Page"
  Action: "allPages"
  Security: true
  # Role: [admin]

# /dashboard/update-page:
#   Controller: "Page"
#   Action: "edit"
#   Security: true
#   Role: "user, admin"

# /dashboard/delete-page:
#   Controller: "Page"
#   Action: "delete"
#   Security: true
#   Role: "admin"


# COMMENTS

/dashboard/comments:
  Controller: "Comment"
  Action: "allComments"
  Security: true
  # Role: [admin]

/dashboard/add-comment:
  Controller: "Comment"
  Action: "addComment"
  Security: true
  # Role: "admin"

# /dashboard/update-comment:
#   Controller: "Comment"
#   Action: "edit"
#   Security: true
#   Role: "user"

# /dashboard/delete-comment:
#   Controller: "Comment"
#   Action: "delete"
#   Security: true
#   Role: "admin"


# TAGS
/dashboard/tags/tag:
  Controller: "Tag"
  Action: "addTag"
  Security: true
  # Role: "admin"

/dashboard/tags:
  Controller: "Tag"
  Action: "allTags"
  Security: true
  # Role: [admin]

# /dashboard/update-tag:
#   Controller: "Tag"
#   Action: "edit"
#   Security: true
#   Role: "admin"

# /dashboard/delete-tag:
#   Controller: "Category"
#   Action: "delete"
#   Security: true
#   Role: "admin"


# MEDIAS
/dashboard/medias:
  Controller: "Media"
  Action: "allMedias"
  Security: true
  # Role: [admin]

/dashboard/add-media:
  Controller: "Media"
  Action: "addMedia"
  Security: true
  # Role: "admin"

# /dashboard/update-media:
#   Controller: "Media"
#   Action: "edit"
#   Security: true
#   Role: "admin"

# /dashboard/delete-media:
#   Controller: "Media"
#   Action: "delete"
#   Security: true
#   Role: "admin"




# SETTING
/dashboard/settings:
  Controller: "Setting"
  Action: "setSetting"
  Security: true
  # Role: [admin]


# INSTALLER
/install:
  Controller: "Installer"
  Action: "Install"



# Ajout de page dynamique pour le front ?
# /page-title:
#   Controller: "Main"
#   Action: "show"
#   Security: false
#   Role: ""

# /project-name:
#   Controller: "Main"
#   Action: "show"
#   Security: false
#   Role: ""

# /user-name:
#   Controller: "Main"
#   Action: "show"
#   Security: false
#   Role: ""
<<<<<<< HEAD
=======

# Utile ? -> étant donné que ça va être en bas de page ??
/add-comment:
  Controller: "Page"
  Action: "add"
  Security: true
  Role: "user"

/update-commanent:
  Controller: "Comment"
  Action: "edit"
  Security: true
  Role: "user"
>>>>>>> 831169c (mise en place des formulaires)


# USER
/login:
  Controller: "Security"
  Action: "login"

/register:
  Controller: "Security"
  Action: "register"

/activate-account:
  Controller: "Security"
  Action: "activateAccount"

/logout:
  Controller: "Security"
  Action: "logout"

<<<<<<< HEAD
/reset-password:
=======


/reinitialization:
  Controller: "Reinitialization"
  Action: "reinitialization"

/add-user:
  Controller: "User"
  Action: "add"
  Security: true
  Role: "admin"

# Utilité de la suppression de l'utilisateur
/delete-user:
  Controller: "User"
  Action: "delete"
  Security: true
  Role: "admin, user"

/list-user:
  Controller: "User"
  Action: "list"
  Security: true
  Role: "admin"

/update-user:
  Controller: "User"
  Action: "edit"
  Security: true
  Role: "user, admin"

# PROJECT
/login:
>>>>>>> 831169c (mise en place des formulaires)
  Controller: "Security"
  Action: "resetPassword"

/request-password:
  Controller: "Security"
<<<<<<< HEAD
  Action: "requestPassword"
=======
  Action: "register"
  Security: false
  Role: ""

/add-user:
  Controller: "User"
  Action: "add"
  Security: true
  Role: "admin"

/delete-user:
  Controller: "User"
  Action: "delete"
  Security: true
  Role: "admin, user"

/list-user:
  Controller: "User"
  Action: "list"
  Security: true
  Role: "admin"

/update-user:
  Controller: "User"
  Action: "edit"
  Security: true
  Role: "user, admin"

# PAGE

#Même chose ??
/add-page:
  Controller: "Page"
  Action: "add"
  Security: true
  Role: "admin"
 
/update-page:
  Controller: "Page"
  Action: "edit"
  Security: true
  Role: "user, admin"

/delete-page:
  Controller: "Page"
  Action: "delete"
  Security: true
  Role: "admin"

/list-page:
  Controller: "Page"
  Action: "list"
  Security: true
  Role: "admin"

# COMMENTAIRES
/delete-comment:
  Controller: "Comment"
  Action: "delete"
  Security: true
  Role: "admin"

/list-comment:
  Controller: "Comment"
  Action: "list"
  Security: true
  Role: "admin"

# CATEGORIES
/add-category:
  Controller: "Category"
  Action: "add"
  Security: true
  Role: "admin"
 
/update-category:
  Controller: "Category"
  Action: "edit"
  Security: true
  Role: "admin"

/delete-category:
  Controller: "Category"
  Action: "delete"
  Security: true
  Role: "admin"

/list-category:
  Controller: "Category"
  Action: "list"
  Security: true
  Role: "admin"

# MEDIAS
/add-media:
  Controller: "Media"
  Action: "add"
  Security: true
  Role: "admin"
 
/update-media:
  Controller: "Media"
  Action: "edit"
  Security: true
  Role: "admin"

/delete-media:
  Controller: "Media"
  Action: "delete"
  Security: true
  Role: "admin"

/list-media:
  Controller: "Media"
  Action: "list"
  Security: true
  Role: "admin"

# SETTING
/settings:
  Controller: "Settings"
  Action: "Add"
  Security: true
  Role: "admin"

# INSTALLER
/install:
  Controller: "Installer"
  Action: "Install"
  Security: false
  Role: ""
>>>>>>> 831169c (mise en place des formulaires)
